# Generated by Django 3.1.1 on 2020-12-09 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestor', '0004_auto_20201204_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestor',
            name='echo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='requestor',
            name='other_expense',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='requestor',
            name='remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='requestor',
            name='scho_donor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='requestor',
            name='service_obligation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='requestor',
            name='training_report',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
