# Generated by Django 3.1.1 on 2020-09-23 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='login.roles'),
        ),
    ]
