# Generated by Django 3.1.1 on 2020-12-03 02:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import requestor.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(max_length=100)),
                ('shortterm', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Requestor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reference_scholarship', models.CharField(blank=True, default='Auto Assign', max_length=500, verbose_name='Reference')),
                ('date_filed', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date_filed')),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('prog_title', models.CharField(max_length=50)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', validators=[requestor.validators.validate_file_extension])),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('req_action', models.CharField(default=0, max_length=50)),
                ('name_title', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('first_name', models.CharField(default='', max_length=100)),
                ('middle_initial', models.CharField(default='', max_length=100)),
                ('nickname', models.CharField(default='', max_length=100)),
                ('position', models.CharField(default='', max_length=100)),
                ('salary_grade', models.CharField(default='', max_length=100)),
                ('office', models.CharField(default='', max_length=100)),
                ('e_mail', models.EmailField(default='', max_length=100)),
                ('mobile_no', models.CharField(default='', max_length=100)),
                ('office_no', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='', max_length=10)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('civil_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('legally separated', 'Legally Separated'), ('annulled', 'Annulled'), ('widowed', 'Widowed')], default='', max_length=20)),
                ('disability', models.CharField(blank=True, max_length=100, null=True)),
                ('ethnicity', models.CharField(blank=True, max_length=100, null=True)),
                ('duties', models.CharField(blank=True, max_length=400, null=True)),
                ('pending_scholarship', models.CharField(choices=[('True', 'Yes'), ('False', 'No')], max_length=10, null=True)),
                ('scholarship_title', models.CharField(max_length=100, null=True)),
                ('pending_reentry_action_plan', models.CharField(blank=True, choices=[('True', 'Yes'), ('False', 'No')], max_length=10, null=True)),
                ('reap_title', models.CharField(blank=True, max_length=100, null=True)),
                ('personal_data_sheet', models.FileField(blank=True, null=True, upload_to='pds/%Y/%m/%d/', validators=[requestor.validators.validate_file_extension])),
                ('individual_performance_commitment_and_review', models.FileField(blank=True, null=True, upload_to='ipcr/%Y/%m/%d/', validators=[requestor.validators.validate_file_extension])),
                ('potential_assessment_form', models.FileField(blank=True, null=True, upload_to='paf/%Y/%m/%d/', validators=[requestor.validators.validate_file_extension])),
                ('checkbox_certify', models.BooleanField(default='False', verbose_name='Certify')),
                ('checkbox_ack', models.BooleanField(default='False', verbose_name='Acknowledgement')),
                ('checkbox_agree', models.BooleanField(default='False', verbose_name='Agree')),
                ('assigned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='requestor.category', verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategories', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SupportCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShortTerm', models.CharField(max_length=10, null=True)),
                ('supportcategories', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TermsCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkbox_certify', models.BooleanField(verbose_name='I certify that the above is true and correct to the best of my knowledge')),
                ('checkbox_ack', models.BooleanField(default='False', verbose_name='I acknowledge and accept the condition that without the\n                   original copies of all the signed forms herewith uploaded,\n                   no travel order/authority will be issued to me. ')),
                ('checkbox_agree', models.BooleanField(default='False', verbose_name='I agree with the DOTr Data Privacy Policy')),
                ('requestor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='requestor.requestor')),
            ],
        ),
        migrations.CreateModel(
            name='SectorForScholarship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sectorforscholarship', models.CharField(max_length=100)),
                ('shortterm', models.CharField(max_length=10, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sector_for_scholarship_set', to='requestor.category')),
            ],
        ),
        migrations.CreateModel(
            name='Scholarship_Requirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_data_sheet', models.FileField(blank=True, null=True, upload_to='pds/%Y/%m/%d/', validators=[requestor.validators.validate_file_extension])),
                ('individual_performance_commitment_and_review', models.FileField(blank=True, null=True, upload_to='ipcr/%Y/%m/%d/', validators=[requestor.validators.validate_file_extension])),
                ('potential_assessment_form', models.FileField(blank=True, null=True, upload_to='paf/%Y/%m/%d/', validators=[requestor.validators.validate_file_extension])),
                ('requestor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='requestor.requestor')),
            ],
        ),
        migrations.CreateModel(
            name='RequestorLog',
            fields=[
                ('log_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('change_msg', models.CharField(max_length=100)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='requestor.status', verbose_name='content')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Users')),
            ],
        ),
        migrations.AddField(
            model_name='requestor',
            name='sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='requestor.sector', verbose_name='Sector'),
        ),
        migrations.AddField(
            model_name='requestor',
            name='sector_for_scholarship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='requestor.sectorforscholarship', verbose_name='Sector'),
        ),
        migrations.AddField(
            model_name='requestor',
            name='status',
            field=models.ForeignKey(blank=True, default=4, null=True, on_delete=django.db.models.deletion.SET_NULL, to='requestor.status'),
        ),
        migrations.AddField(
            model_name='requestor',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='requestor.subcategory', verbose_name='Sub Category'),
        ),
        migrations.AddField(
            model_name='requestor',
            name='supportcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='requestor.supportcategory', verbose_name='Support Category'),
        ),
        migrations.AddField(
            model_name='requestor',
            name='user',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Nomination_Form',
            fields=[
                ('nomination_id', models.AutoField(primary_key=True, serialize=False)),
                ('name_title', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_initial', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('salary_grade', models.CharField(max_length=100)),
                ('office', models.CharField(max_length=100)),
                ('e_mail', models.EmailField(max_length=100)),
                ('mobile_no', models.CharField(max_length=100)),
                ('office_no', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='', max_length=10)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('civil_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('legally separated', 'Legally Separated'), ('annulled', 'Annulled'), ('widowed', 'Widowed')], default='', max_length=20)),
                ('disability', models.CharField(blank=True, max_length=100, null=True)),
                ('ethnicity', models.CharField(blank=True, max_length=100, null=True)),
                ('duties', models.CharField(blank=True, max_length=400, null=True)),
                ('requestor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='requestor.requestor')),
            ],
        ),
        migrations.CreateModel(
            name='Eligibility_Status',
            fields=[
                ('eligibility_id', models.AutoField(primary_key=True, serialize=False)),
                ('pending_scholarship', models.CharField(choices=[('True', 'Yes'), ('False', 'No')], max_length=10)),
                ('scholarship_title', models.CharField(max_length=100)),
                ('pending_reentry_action_plan', models.CharField(choices=[('True', 'Yes'), ('False', 'No')], max_length=10)),
                ('reap_title', models.CharField(max_length=100)),
                ('requestor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='requestor.requestor')),
            ],
        ),
    ]
