# Generated by Django 3.1.1 on 2020-12-04 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requestor', '0003_auto_20201203_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestor',
            name='echo',
        ),
        migrations.RemoveField(
            model_name='requestor',
            name='other_expense',
        ),
        migrations.RemoveField(
            model_name='requestor',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='requestor',
            name='scho_donor',
        ),
        migrations.RemoveField(
            model_name='requestor',
            name='service_obligation',
        ),
        migrations.RemoveField(
            model_name='requestor',
            name='training_report',
        ),
    ]
