# Generated by Django 3.1.4 on 2021-02-01 06:03

from django.db import migrations, models
import requestor.validators


class Migration(migrations.Migration):

    dependencies = [
        ('requestor', '0006_requestor_last_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestor',
            name='incrementor',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='requestor',
            name='justification',
            field=models.FileField(blank=True, null=True, upload_to='justification/%Y/%m/%d/', validators=[requestor.validators.validate_file_extension]),
        ),
    ]
