# Generated by Django 3.1.4 on 2021-02-04 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requestor', '0007_auto_20210201_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestor',
            name='status',
            field=models.ForeignKey(blank=True, default=6, null=True, on_delete=django.db.models.deletion.SET_NULL, to='requestor.status'),
        ),
    ]
