# Generated by Django 3.1.4 on 2021-02-04 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestor', '0008_auto_20210204_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestor',
            name='lacking_documents',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='requestor',
            name='ta_signed_upload',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
