# Generated by Django 3.1.4 on 2021-02-08 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestor', '0010_requestor_taketimestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestor',
            name='followup',
            field=models.BooleanField(choices=[(1, 'True'), (0, 'False')], default='False', verbose_name='Follow up to HRDD'),
        ),
    ]
