# Generated by Django 3.1.1 on 2021-06-09 00:35

from django.db import migrations, models
import requestor.validators


class Migration(migrations.Migration):

    dependencies = [
        ('requestor', '0012_auto_20210304_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestor',
            name='sa_signed_upload',
            field=models.FileField(blank=True, null=True, upload_to='sa_signed_upload/%Y/%m/%d/', validators=[requestor.validators.validate_file_extension]),
        ),
    ]
