# Generated by Django 3.1.1 on 2020-09-08 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='anntbl',
            fields=[
                ('anid', models.AutoField(primary_key=True, serialize=False)),
                ('upload', models.ImageField(blank=True, null=True, upload_to='uploads/')),
            ],
        ),
    ]
