# Generated by Django 3.1.1 on 2020-09-08 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='anntbl',
        ),
    ]
