# Generated by Django 3.1.1 on 2020-11-25 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='travel_sector1',
            fields=[
                ('sec1_id', models.AutoField(primary_key=True, serialize=False)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
