# Generated by Django 3.1.1 on 2020-11-25 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelauth', '0003_delete_travel_sector1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelrequest_tbl',
            name='sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='travelauth.travel_sector'),
        ),
    ]
