# Generated by Django 3.1.1 on 2020-12-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelauth', '0006_travelrequest_tbl_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelrequest_tbl',
            name='ta_signed_upload',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
