# Generated by Django 3.1.1 on 2020-12-03 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelauth', '0008_auto_20201203_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelrequest_tbl',
            name='assigned',
        ),
    ]
