# Generated by Django 3.1.1 on 2020-12-18 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelauth', '0013_auto_20201218_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelrequest_tbl',
            name='lacking_documents',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
