# Generated by Django 3.1.4 on 2021-01-15 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelauth', '0015_auto_20210104_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelrequest_tbl',
            name='cancel_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
