# Generated by Django 3.1.4 on 2021-01-18 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelauth', '0016_travelrequest_tbl_cancel_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_category',
            name='shorterm',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
