# Generated by Django 3.1.4 on 2021-01-18 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelauth', '0017_request_category_shorterm'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelrequest_tbl',
            name='incrementor',
            field=models.IntegerField(default=0),
        ),
    ]
