# Generated by Django 3.1.4 on 2021-02-02 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelauth', '0022_travelrequest_tbl_with_issues'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelrequest_tbl',
            name='taketimestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
