# Generated by Django 3.1.4 on 2021-02-02 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelauth', '0023_travelrequest_tbl_taketimestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelrequest_tbl',
            name='t_report',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
