# Generated by Django 3.1.4 on 2021-02-03 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelauth', '0024_travelrequest_tbl_t_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelrequest_tbl',
            name='name_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
