# Generated by Django 3.1.4 on 2021-02-04 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelauth', '0025_travelrequest_tbl_name_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelrequest_tbl',
            name='email_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='travelrequest_tbl',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='travelrequest_tbl',
            name='office_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
