# Generated by Django 3.1.4 on 2021-02-04 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelauth', '0026_auto_20210204_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelrequest_tbl',
            name='salary_grade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
