# Generated by Django 3.1.4 on 2021-02-04 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelauth', '0027_travelrequest_tbl_salary_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelrequest_tbl',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
