# Generated by Django 3.1.4 on 2021-02-04 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelauth', '0028_travelrequest_tbl_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelrequest_tbl',
            name='age',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
