# Generated by Django 3.1.1 on 2020-11-25 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='History_tbl',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('a_officer', models.CharField(blank=True, max_length=100, null=True)),
                ('travelreq_id', models.CharField(blank=True, max_length=100, null=True)),
                ('eval_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='request_category',
            fields=[
                ('catt_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_category', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='travel_sector',
            fields=[
                ('sec_id', models.AutoField(primary_key=True, serialize=False)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TravelRequest_tbl',
            fields=[
                ('travelreq_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_filed', models.DateTimeField(default=django.utils.timezone.now)),
                ('sub_category', models.CharField(blank=True, max_length=100, null=True)),
                ('support_category', models.CharField(blank=True, max_length=100, null=True)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('program_title', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('middle_initial', models.CharField(blank=True, max_length=100, null=True)),
                ('suffix', models.CharField(blank=True, max_length=100, null=True)),
                ('nickname', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
                ('civil_status', models.CharField(blank=True, max_length=100, null=True)),
                ('disability', models.CharField(blank=True, max_length=100, null=True)),
                ('ethnicity', models.CharField(blank=True, max_length=100, null=True)),
                ('agency', models.CharField(blank=True, max_length=100, null=True)),
                ('destination', models.CharField(blank=True, max_length=100, null=True)),
                ('programdates_from', models.CharField(blank=True, max_length=100, null=True)),
                ('programdates_to', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, default=0, max_length=100, null=True)),
                ('cancel_mess', models.CharField(blank=True, max_length=100, null=True)),
                ('ic_endorsement', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('ic_icd', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('ic_invitation', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('ic_no_pending_task', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('ic_no_admin_case', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('ic_service_record', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('ic_funds', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('ic_expenses', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('ic_unliquidated', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('ic_retirement', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('ic_undertaking', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('mc_endorsement', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('mc_icd', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('mc_invitation', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('mc_no_pending_task', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('mc_no_admin_case', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('mc_service_record', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('mc_funds', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('mc_expenses', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('mc_unliquidated', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('mc_retirement', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('mc_undertaking', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('ts_endorsement', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('ts_icd', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('ts_invitation', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('ts_acceptance', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('ts_minutes', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('ts_scholarship', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('ts_no_pending_task', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('ts_no_admin_case', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('ts_service_record', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('ts_funds', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('ts_expenses', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('ts_unliquidated', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('ts_retirement', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('ts_undertaking', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('ts_report', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('fi_endorsement', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('fi_icd', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('fi_invitation', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('fi_agreement', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('fi_no_pending_task', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('fi_no_admin_case', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('fi_service_record', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('fi_funds', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('fi_expenses', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('fi_unliquidated', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('fi_retirement', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('fi_undertaking', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('pt_icd', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('pt_no_pending_task', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('pt_no_admin_case', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('pt_service_record', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('pt_leave_application', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('pt_clearance', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('request_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='travelauth.request_category')),
                ('requestor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
