# Generated by Django 3.1.1 on 2020-11-25 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelauth', '0002_travel_sector1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='travel_sector1',
        ),
    ]
