# Generated by Django 3.1.1 on 2020-11-26 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelauth', '0004_auto_20201125_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='travel_office',
            fields=[
                ('off_id', models.AutoField(primary_key=True, serialize=False)),
                ('office', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
