# Generated by Django 3.1.4 on 2021-01-04 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelauth', '0014_travelrequest_tbl_lacking_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelrequest_tbl',
            name='t_ipcr',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='travelrequest_tbl',
            name='t_paf',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='travelrequest_tbl',
            name='t_pds',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='travelrequest_tbl',
            name='t_pre_registration',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
