# Generated by Django 3.1.4 on 2021-01-18 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelauth', '0018_travelrequest_tbl_incrementor'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_category',
            name='true_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
