# Generated by Django 3.1.4 on 2021-01-19 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelauth', '0019_request_category_true_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelrequest_tbl',
            name='additional_requirement_1',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='travelrequest_tbl',
            name='additional_requirement_2',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
