# Generated by Django 3.1.4 on 2021-01-26 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelauth', '0020_auto_20210119_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelrequest_tbl',
            name='unsigned_docs',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='travelrequest_tbl',
            name='wrong_attachment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
