# Generated by Django 3.1.4 on 2021-01-28 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelauth', '0021_auto_20210126_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelrequest_tbl',
            name='with_issues',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
