# Generated by Django 3.1.4 on 2021-02-04 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelauth', '0029_travelrequest_tbl_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='history_tbl',
            name='scholar_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
