# Generated by Django 3.1.4 on 2021-02-05 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelauth', '0030_history_tbl_scholar_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelrequest_tbl',
            name='nt_allowance',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='travelrequest_tbl',
            name='nt_invitation',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='travelrequest_tbl',
            name='nt_others',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='travelrequest_tbl',
            name='nt_transportation',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
