# Generated by Django 3.1.4 on 2021-02-08 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelauth', '0031_auto_20210205_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelrequest_tbl',
            name='followup',
            field=models.BooleanField(choices=[(1, 'True'), (0, 'False')], default='False', verbose_name='Follow up to HRDD'),
        ),
    ]
