# Generated by Django 3.1.4 on 2021-02-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelauth', '0032_travelrequest_tbl_followup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pending_training_report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('middle_initial', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
