# Generated by Django 3.1.4 on 2021-02-09 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelauth', '0033_pending_training_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='pending_training_report',
            name='course_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pending_training_report',
            name='duration_in_days',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pending_training_report',
            name='echo_seminar_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pending_training_report',
            name='gender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pending_training_report',
            name='office',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pending_training_report',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pending_training_report',
            name='post_report_submit_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pending_training_report',
            name='program_fee',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pending_training_report',
            name='programdates_from',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pending_training_report',
            name='programdates_to',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pending_training_report',
            name='remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pending_training_report',
            name='training_institution',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
