# Generated by Django 3.1.4 on 2021-02-09 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelauth', '0034_auto_20210210_0737'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pending_remarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
