# Generated by Django 3.1.4 on 2021-02-09 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelauth', '0035_pending_remarks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pending_remarks',
            old_name='remark',
            new_name='remarks',
        ),
    ]
