# Generated by Django 3.1.4 on 2021-02-09 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelauth', '0036_auto_20210210_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pending_training_report',
            name='remarks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='travelauth.pending_remarks'),
        ),
    ]
