# Generated by Django 3.1.4 on 2021-02-10 00:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelauth', '0037_auto_20210210_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pending_training_report',
            name='echo_seminar_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='pending_training_report',
            name='post_report_submit_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='pending_training_report',
            name='programdates_from',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='pending_training_report',
            name='programdates_to',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
