# Generated by Django 3.1.4 on 2021-03-31 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelauth', '0038_auto_20210210_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelrequest_tbl',
            name='pptr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
