# Generated by Django 3.1.1 on 2021-06-09 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelauth', '0039_travelrequest_tbl_pptr'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelrequest_tbl',
            name='nt_without_gov_expense',
            field=models.IntegerField(default=0),
        ),
    ]
