# Generated by Django 3.1.1 on 2021-06-10 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelauth', '0040_travelrequest_tbl_nt_without_gov_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelrequest_tbl',
            name='nt_without_gov_expense',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
