# Generated by Django 3.1.1 on 2021-06-15 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelauth', '0041_auto_20210610_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelrequest_tbl',
            name='nt_gov_expense_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
